name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 21.1.0
      uses: actions/setup-node@v3
      with:
        node-version: '21.1.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test

    - name: Build
      run: npm run build

    - name: Publish to npm as Beta
      run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
